server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server}/eureka/
  #关闭断路保护
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
